improve ssh setup logic

diff --git a/hooks/checkout b/hooks/checkout
--- a/hooks/checkout
+++ b/hooks/checkout
@@ -16,7 +16,17 @@ echo "Setup completed successfully."
 
 
 echo "--- :key: Setting up git and ssh"
-mkdir -p "$HOME/.ssh" && ssh-keyscan -t rsa github.com >> "$HOME/.ssh/known_hosts"
+if ! ssh-keygen -F github.com > /dev/null; then
+  echo "github.com not found in known_hosts"
+  mkdir -p /tmp && ssh-keyscan -t rsa github.com > /tmp/github_rsa.pub
+  GH_PUBKEY_FINGERPRINT="$(ssh-keygen -lf /tmp/github_rsa.pub | awk '{ print $2 }')"
+  if [ "$GH_PUBKEY_FINGERPRINT" != "SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8" ]; then
+    echo "FATAL: got wrong public key from keyscan"
+    exit 1
+  fi
+  mkdir -p $HOME/.ssh cat /tmp/github_pub.rsa >> $HOME/.ssh/known_hosts
+  echo "github.com added to known_hosts"
+fi
 
 echo "--- :git: Checking out repository"
 CLONE_URL=${BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_CLONE_URL:-$BUILDKITE_REPO}
