polish

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -8,32 +8,27 @@ if [[ "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_SKIP_CHECKOUT" == "true" \
 fi
 
 echo "Removing checkout directory: $BUILDKITE_BUILD_CHECKOUT_PATH"
-
-echo "before rm -rf of $BUILDKITE_BUILD_CHECKOUT_PATH"
-
-rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" || true
-
-echo "after rm -rf of $BUILDKITE_BUILD_CHECKOUT_PATH"
-
-if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
+# redirecting rm's stderr to /dev/null
+# because it would pollute the logs if there were a lot of files inside the folder to be removed.
+# Example: `node_modules` folder created by a different user in a container during a build throwing
+# permission error for each of the files inside it.
+rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" 2>/dev/null || {
   echo "Tried running: rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
   echo "But it failed leaving the following files as residue"
-  ls -la $BUILDKITE_BUILD_CHECKOUT_PATH
-fi
-
-echo "after first check"
+  ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
+}
 
 if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
-  echo "Trying to cleanup $BUILDKITE_BUILD_CHECKOUT_PATH using sudo"
-  sudo -n rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH"
+  echo echo "Attempting to cleanup with sudo"
+  sudo -n rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" || {
+    echo "Tried running: sudo -n rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
+    echo "But it failed leaving the following files as residue"
+    ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
+  }
 fi
 
-echo "after second check"
-
-if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
-  echo "Cleanup was not successful."
-else
+if [ ! -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
   echo "Cleanup completed successfully."
+else
+  echo "Cleanup was not successful."
 fi
-
-echo "finally"
