Revert "comment out normal rm to check sudo rm"
This reverts commit aecd7ccdff582e0f10734ce80604d5f7215aad8c.

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -12,11 +12,11 @@ echo "Removing checkout directory: $BUILDKITE_BUILD_CHECKOUT_PATH"
 # because it would pollute the logs if there were a lot of files inside the folder to be removed.
 # Example: `node_modules` folder created by a different user in a container during a build throwing
 # permission error for each of the files inside it.
-# rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" 2>/dev/null || {
-#   echo "Tried running: rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
-#   echo "But it failed leaving the following files as residue"
-#   ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
-# }
+rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" 2>/dev/null || {
+  echo "Tried running: rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
+  echo "But it failed leaving the following files as residue"
+  ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
+}
 
 if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
   echo echo "Attempting to cleanup with sudo"
