refactor cleanup section to avoid 'stop the world' sudo command

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -8,7 +8,20 @@ if [[ "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_SKIP_CHECKOUT" == "true" \
 fi
 
 echo "Removing checkout directory: $BUILDKITE_BUILD_CHECKOUT_PATH"
-# Only try sudo if deleting without sudo fails
-rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" 2>/dev/null \
-  || sudo rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH"
-echo "Cleanup completed successfully."
+
+rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" 2>/dev/null || {
+  echo "Tried running: rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
+  echo "But it failed leaving the following files as residue"
+  ls -la $BUILDKITE_BUILD_CHECKOUT_PATH
+}
+
+if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
+  echo "Trying to cleanup $BUILDKITE_BUILD_CHECKOUT_PATH using sudo"
+  sudo -n rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH"
+fi
+
+if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
+  echo "Cleanup was not successful."
+else
+  echo "Cleanup completed successfully."
+fi
